# Generated by Django 6.0.4 on 2026-06-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('workspaces', '0005_alter_teammembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this announcement targets. Null = workspace-wide announcement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='workspaces.team'),
        ),
    ]
