# Generated by Django 6.0.4 on 2026-06-19 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_deleted_at_announcement_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user'], name='announcemen_user_id_e7ced7_idx'),
        ),
    ]
