# Generated by Django 6.0.4 on 2026-06-23 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcementread_announcemen_user_id_e7ced7_idx'),
        ('workspaces', '0010_team_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='announcementread',
            name='announcemen_user_id_e7ced7_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='team',
        ),
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='workspaces.team'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='workspaces.workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
