# Generated by Django 6.0.4 on 2026-06-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcementattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
