# Generated by Django 6.0.4 on 2026-07-07 17:32

import django.core.validators
import django.db.models.deletion
import notes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Note', help_text='Title of the note.', max_length=200)),
                ('content', models.TextField(blank=True, help_text="The note's content. Supports plain text and markdown.")),
                ('is_favorite', models.BooleanField(db_index=True, default=False, help_text='Whether this note is marked as a favorite.')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Whether this note is pinned to the top.')),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of string tags for categorization (e.g., ['urgent', 'work']).")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the note was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the note was last updated.')),
                ('user', models.ForeignKey(help_text='The user who owns this note.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=notes.models.note_attachment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notes.note')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the notebook.', max_length=100)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for notebook display (e.g., #6366f1).', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Color must be a valid hex color code (e.g., #FF5733).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notebook was created.')),
                ('user', models.ForeignKey(help_text='The user who owns this notebook.', on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(blank=True, help_text='Optional notebook this note belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.notebook'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-is_pinned', '-updated_at'], name='notes_note_user_id_cea72d_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='notes_note_user_id_d67ab6_idx'),
        ),
    ]
