# Generated by Django 6.0.4 on 2026-06-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_team'),
        ('workspaces', '0005_alter_teammembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('team', 'Team')], default='personal', help_text='Personal tasks are private. Team tasks are visible to all team members.', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Required for team tasks. Must be null for personal tasks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.team'),
        ),
    ]
