# Generated by Django 6.0.4 on 2026-06-10 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_archive_after_task_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('assigned', 'Assigned'), ('team', 'Team')], default='personal', help_text='Personal tasks are private. Assigned tasks are collaborative.', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('updated', 'Updated'), ('approved', 'Approved'), ('overdue', 'Overdue'), ('archived', 'Archived')], max_length=20),
        ),
        migrations.CreateModel(
            name='TaskMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task', 'user')},
            },
        ),
    ]
