# Generated by Django 6.0.4 on 2026-06-19 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskmember_unique_together_task_deleted_at_and_more'),
        ('workspaces', '0010_team_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'status'], name='tasks_task_workspa_58e2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'task_type'], name='tasks_task_workspa_9108e1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'assigned_to'], name='tasks_task_workspa_42f81e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'created_by'], name='tasks_task_workspa_4ce681_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'team'], name='tasks_task_workspa_7eff37_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_deleted', 'is_archived'], name='tasks_task_is_dele_235814_idx'),
        ),
    ]
