# Generated by Django 6.0.4 on 2026-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='all_notifications_muted',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='channel_invites_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='dm_requests_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='mentions_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='task_assignments_enabled',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('chat_created', 'Chat Created'), ('channel_joined', 'Channel Joined'), ('message_received', 'Message Received'), ('mention', 'Mention'), ('task_assigned', 'Task Assigned'), ('announcement', 'Announcement'), ('workspace_event', 'Workspace Event'), ('dm_request', 'DM Request'), ('dm_request_accepted', 'DM Request Accepted'), ('channel_invite', 'Channel Invite')], max_length=50),
        ),
    ]
