# Generated by Django 6.0.4 on 2026-06-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_duration_alter_attendance_date_and_more'),
        ('workspaces', '0010_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='workspaces.workspace'),
        ),
    ]
