# Generated by Django 6.0.4 on 2026-06-23 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_workspaceattendanceconfig_alter_attendance_options_and_more'),
        ('workspaces', '0010_team_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date', 'workspace')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('working', 'Working'), ('on_break', 'On Break'), ('checked_out', 'Checked Out'), ('calculated', 'Calculated'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('locked', 'Locked'), ('absent', 'Absent'), ('leave', 'On Leave'), ('holiday', 'Holiday')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='workspaces.workspace'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('attendance', 'Attendance'), ('leave', 'Leave'), ('expense', 'Expense'), ('manual_correction', 'Manual Correction')], max_length=30)),
                ('entity_id', models.PositiveIntegerField()),
                ('request_type', models.CharField(choices=[('late', 'Late Arrival'), ('missing_checkout', 'Missing Checkout'), ('overtime', 'Overtime'), ('manual_edit', 'Manual Edit')], max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_resolved', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='attendance.attendance')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('late', 'Late Arrival'), ('early_departure', 'Early Departure'), ('half_day', 'Half Day'), ('overtime', 'Overtime'), ('manual_edit', 'Manual Edit'), ('weekend', 'Weekend Work'), ('holiday', 'Holiday Work'), ('remote', 'Remote Work'), ('correction_requested', 'Correction Requested')], max_length=30)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='attendance.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_type', models.CharField(choices=[('strict', 'Strict'), ('flexible', 'Flexible'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='strict', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('minimum_daily_hours', models.FloatField(default=8.0)),
                ('maximum_daily_hours', models.FloatField(default=12.0)),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('allow_multiple_sessions', models.BooleanField(default=True)),
                ('allow_breaks', models.BooleanField(default=True)),
                ('allow_overtime', models.BooleanField(default=False)),
                ('require_location', models.BooleanField(default=False)),
                ('require_office_ip', models.BooleanField(default=False)),
                ('auto_checkout_policy', models.CharField(default='none', max_length=20)),
                ('rounding_policy', models.CharField(default='none', max_length=20)),
                ('weekend_policy', models.CharField(default='off', max_length=20)),
                ('holiday_policy', models.CharField(default='off', max_length=20)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-version'],
                'get_latest_by': 'version',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('work', 'Work'), ('break', 'Break'), ('meeting', 'Meeting'), ('training', 'Training')], default='work', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('remote', 'Remote'), ('vpn', 'VPN'), ('gps', 'GPS')], default='remote', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.attendance')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calendars', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='attendance.holidaycalendar')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_overnight', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='workspaces.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shifttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shifttemplate'),
        ),
        migrations.DeleteModel(
            name='WorkspaceAttendanceConfig',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='edit_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_half_day',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_late',
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['workspace', 'status'], name='attendance__workspa_1655b9_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['entity_type', 'entity_id'], name='attendance__entity__2ec59a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceflag',
            unique_together={('attendance', 'flag_type')},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('calendar', 'date')},
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['user', 'effective_from'], name='attendance__user_id_d6a818_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['team', 'effective_from'], name='attendance__team_id_00f7ab_idx'),
        ),
    ]
