# Generated by Django 6.0.4 on 2026-06-23 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_unique_together_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspaces', '0010_team_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('burnout', 'Burnout Risk'), ('absenteeism', 'Absenteeism Pattern'), ('late_trend', 'Late Trend'), ('shift_rec', 'Shift Recommendation')], max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('manual_edit', 'Manual Edit'), ('geo_exception', 'Geo Exception'), ('ai_suspicious', 'AI Suspicious'), ('correction_requested', 'Correction Requested'), ('policy_override', 'Policy Override')], max_length=30)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendanceflag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendanceflag',
            name='attendance',
        ),
        migrations.RemoveIndex(
            model_name='approvalrequest',
            name='attendance__entity__2ec59a_idx',
        ),
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='entity_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='shift',
            new_name='shift_template',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='expected_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='productive_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendanceinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceinsight',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_insights', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='attendancetag',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='attendance.attendance'),
        ),
        migrations.DeleteModel(
            name='AttendanceFlag',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='entity_type',
        ),
    ]
