# Generated by Django 6.0.4 on 2026-06-23 22:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendanceinsight_attendancetag_and_more'),
        ('workspaces', '0010_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAttendanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(default='09:00')),
                ('shift_end', models.TimeField(default='18:00')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('working_days', models.CharField(default='0,1,2,3,4', max_length=20)),
                ('half_day_threshold', models.DurationField(default=datetime.timedelta(seconds=14400))),
            ],
        ),
        migrations.RemoveIndex(
            model_name='approvalrequest',
            name='attendance__workspa_1655b9_idx',
        ),
        migrations.RemoveField(
            model_name='attendanceaudit',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendanceaudit',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='attendanceinsight',
            name='user',
        ),
        migrations.RemoveField(
            model_name='attendanceinsight',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='attendancepolicy',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendancetag',
            name='attendance',
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='holidaycalendar',
            name='workspace',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='attendance__user_id_d6a818_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='attendance__team_id_00f7ab_idx',
        ),
        migrations.RemoveField(
            model_name='shifttemplate',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='shift_template',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='shift_end',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='shift_start',
            new_name='check_out',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='expected_duration',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_holiday',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_overtime',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_remote',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_weekend',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='overtime_duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='productive_duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='shift_name',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late Arrival'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('leave', 'On Leave'), ('holiday', 'Holiday')], default='absent', max_length=20),
        ),
        migrations.AddField(
            model_name='workspaceattendanceconfig',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_config', to='workspaces.workspace'),
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='AttendanceAudit',
        ),
        migrations.DeleteModel(
            name='AttendanceInsight',
        ),
        migrations.DeleteModel(
            name='AttendancePolicy',
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
        migrations.DeleteModel(
            name='AttendanceTag',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='HolidayCalendar',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='shift_template',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='team',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApprovalRequest',
        ),
        migrations.DeleteModel(
            name='ShiftTemplate',
        ),
        migrations.DeleteModel(
            name='ShiftAssignment',
        ),
    ]
