# Generated by Django 6.0.4 on 2026-07-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_workspaceattendanceconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_out_reason',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTO_SHIFT_END', 'Auto Shift End'), ('ADMIN', 'Admin Override')], max_length=20, null=True),
        ),
    ]
