# Generated by Django 6.0.4 on 2026-07-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_clock_out_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceattendanceconfig',
            name='productivity_cycle_days',
            field=models.PositiveIntegerField(default=14, help_text='Evaluation cycle in days (e.g., 7, 14, 30)'),
        ),
    ]
