# Generated by Django 6.0.4 on 2026-07-04 03:08

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='avatars/', validators=[accounts.models.validate_image_file])),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('appearance_theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', help_text='User interface theme preference.', max_length=20)),
                ('font_size', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('large', 'Large')], default='comfortable', max_length=20)),
                ('compact_mode', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('date_format', models.CharField(default='MM/DD/YYYY', max_length=20)),
                ('time_format', models.CharField(default='24h', max_length=10)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_last_seen', models.BooleanField(default=True)),
                ('allow_dm', models.BooleanField(default=True)),
                ('allow_team_invites', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('workspace', 'Workspace'), ('private', 'Private')], default='workspace', max_length=20)),
                ('notification_preferences', models.JSONField(default=accounts.models.get_default_notification_prefs)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
