# Generated by Django 6.0.4 on 2026-06-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_description_workspace_logo_teammembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_unassigned',
            field=models.BooleanField(default=False, help_text="True if this is the workspace's default unassigned team."),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='unassigned_team',
            field=models.OneToOneField(blank=True, help_text='The default team users are assigned to when they join or are removed from all other teams.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_workspace', to='workspaces.team'),
        ),
    ]
