# Generated by Django 6.0.4 on 2026-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_alter_workspacemembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Description of the team's purpose."),
        ),
    ]
