# Generated by Django 6.0.4 on 2026-06-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#4B1587', help_text='Hex color code for the team avatar/badge.', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Lucide icon name, e.g., 'Users'.", max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If true, team is hidden from non-members.'),
        ),
    ]
