# Generated by Django 6.0.4 on 2026-06-29 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_team_color_team_icon_team_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvite',
            name='invitee',
            field=models.ForeignKey(blank=True, help_text='Specific user invited. Null for generic link invites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_workspace_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspaceinvite',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
