# Generated by Django 6.0.4 on 2026-07-04 03:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_workspaceinvite_invitee_alter_workspaceinvite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='workspace_logos/', validators=[accounts.models.validate_image_file]),
        ),
    ]
