# Generated by Django 6.0.4 on 2026-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_alter_workspace_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='deletion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
    ]
