# Generated by Django 6.0.4 on 2026-07-08 03:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_workspace_deletion_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teaminvite',
            name='idx_teaminvite_lookup',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='workspace/', validators=[accounts.models.validate_image_file]),
        ),
        migrations.DeleteModel(
            name='TeamInvite',
        ),
    ]
