# Generated by Django 6.0.4 on 2026-05-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
