# Generated by Django 6.0.4 on 2026-05-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
