# Generated by Django 6.0.4 on 2026-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_channel_team_channel_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_dm',
            field=models.BooleanField(default=False),
        ),
    ]
