# Generated by Django 6.0.4 on 2026-05-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_notification_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='chat_notifi_recipie_eadc39_idx',
            old_name='chat_notifi_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='chat_notifi_recipie_93a961_idx',
            old_name='chat_notifi_recipie_idx2',
        ),
    ]
