# Generated by Django 6.0.4 on 2026-05-25 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_edited_at_message_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated UUID for idempotency and deduplication', max_length=36, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id', None), _negated=True), fields=('channel', 'client_id'), name='unique_message_client_id_per_channel'),
        ),
    ]
