# Generated by Django 6.0.4 on 2026-06-03 14:08
# MANUALLY EDITED: Safely move Notification models out of chat state without dropping DB tables

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_message_client_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Safely remove Notification from Chat's state ────────────────────
        # This tells Django "the chat app no longer manages these models"
        # but database_operations=[] means "DO NOT drop the actual tables"
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="notification",
                    name="chat_notifi_recipie_eadc39_idx",
                ),
                migrations.RemoveIndex(
                    model_name="notification",
                    name="chat_notifi_recipie_93a961_idx",
                ),
                migrations.RemoveField(
                    model_name="notificationpreference",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="notification",
                    name="actor",
                ),
                migrations.RemoveField(
                    model_name="notification",
                    name="recipient",
                ),
                migrations.RemoveField(
                    model_name="notification",
                    name="workspace",
                ),
                migrations.DeleteModel(
                    name="NotificationPreference",
                ),
                migrations.DeleteModel(
                    name="Notification",
                ),
            ],
            database_operations=[],  # CRITICAL: This prevents dropping the actual tables
        ),
        # ── ChannelMember unique constraint change ──────────────────────────
        migrations.AlterUniqueTogether(
            name="channelmember",
            unique_together=set(),
        ),
        # ── New Channel fields ──────────────────────────────────────────────
        migrations.AddField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("official", "Official Team Chat"),
                    ("private_group", "Private Group"),
                    ("dm", "Direct Message"),
                ],
                default="official",
                help_text="Determines channel behavior and membership rules.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner for private groups. Null for official/DMs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # ── New ChannelMember lifecycle fields ──────────────────────────────
        migrations.AddField(
            model_name="channelmember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="channelmember",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="channelmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("channel", "user"),
                name="unique_active_channel_member",
            ),
        ),
    ]
