# Generated by Django 6.0.4 on 2026-06-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_messageread_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dmrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dmrequest',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, help_text='Sender cannot re-request until this time (30 days after 24h undo window).', null=True),
        ),
        migrations.AddField(
            model_name='dmrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the pending request expires (10 days from creation).', null=True),
        ),
        migrations.AddField(
            model_name='dmrequest',
            name='initial_message',
            field=models.TextField(blank=True, help_text='The single introductory message sent with the DM request.'),
        ),
        migrations.AddField(
            model_name='dmrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the request was rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('official', 'Official Channel'), ('team', 'Team Chat'), ('private_group', 'Private Group'), ('dm', 'Direct Message')], default='official', help_text='Determines channel behavior and membership rules.', max_length=20),
        ),
        migrations.AlterField(
            model_name='dmrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
